spring:
  application:
    name: smart-doc
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:smart_doc}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}
      client:
        github:
          client-id: ${GITHUB_CLIENT_ID:your_github_client_id}
          client-secret: ${GITHUB_CLIENT_SECRET:your_github_client_secret}
          redirectUri: ${GITHUB_REDIRECT_URI:http://localhost:8080/api/auth/callback/github}
#          redirectUri: http://localhost:8080/dashboard
          scope: read:user,user:email
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 50MB

server:
  port: 8080

logging:
  level:
    root: INFO
    com.mtmn.smartdoc: DEBUG

# 应用配置
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # 一天
      refresh-token:
        expiration: 604800000 # 一周
  database:
    initialize: false # 控制是否在启动时初始化数据库表和测试数据

# 模型配置
models:
  # 当前激活的模型
  activeLlm: glm
  activeEmbedding: bge-m3
  
  # 大语言模型配置
  llm:
    glm:
      api-key: ${GLM_API_KEY:your_glm_api_key}
      base-url: https://open.bigmodel.cn/api/paas/v4
      model-name: glm-4-flash
    glm-250414:
      api-key: ${GLM_API_KEY:your_glm_api_key}
      base-url: https://open.bigmodel.cn/api/paas/v4
      model-name: GLM-4-Flash-250414
    chatgpt:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      base-url: https://api.openai.com/v1
      model-name: gpt-4
    gemini:
      api-key: ${GEMINI_API_KEY:your-gemini-api-key}
      base-url: https://generativelanguage.googleapis.com
      model-name: gemini-pro
  
  # 嵌入模型配置
  embedding:
    bge-m3:
      description: 支持 8K 长度的输入
      api-key: ${EMBEDDING_API_KEY:notnull}
      base-url: ${EMBEDDING_BASE_URL:http://localhost:9997/v1/}
      model-name: ${EMBEDDING_MODEL_NAME:bge-m3}
#    openai:
#      description: OpenAI 的嵌入模型
#      api-key: ${OPENAI_API_KEY:your-openai-api-key}
#      base-url: https://api.openai.com/v1
#      model-name: text-embedding-ada-002

# RAG 方法
rag:
  # 默认使用的 RAG 方法
  default-method: naive

  # 普通的RAG方法
  naive:
    name: RAG
    description: 普通的 RAG 方法
    index:
      chunkSize: 512
      chunkOverlap: 100
    search:
      topK: 5

  # HiSem 基础配置
  hisem:
    name: HiSem-RAG-Fast
    description: 层级语义驱动的 RAG 方法（不构建树）
    index:
      chunkSize: 2048
      titleEnhance: true
      anAbstract: false
    search:
      maxRes: 10
    threshold:
      beta: 0.9
      gamma: 0.8
      k_min: 1

  # 使用树结构的高级语义检索方法
  hisemTree:
    name: HiSem-RAG-Tree
    description: 层级语义驱动的 RAG 方法（构建树）
    index:
      chunkSize: 2048
      titleEnhance: true
      anAbstract: true
    search:
      maxRes: 10

# Milvus配置
milvus:
  uri: http://${MILVUS_HOST:localhost}:${MILVUS_PORT:19530}
  host: ${MILVUS_HOST:localhost}
  port: ${MILVUS_PORT:19530}

# MinIO配置
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000} #minio服务地址
  accessKey: ${MINIO_ACCESS_KEY:minioadmin} #minio的用户名
  secretKey: ${MINIO_SECRET_KEY:minioadmin} #minio的密码
  bucket:
    files: smartdoc

# Knife4j 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.mtmn.smartdoc.controller
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
    enable-swagger-models: true
    enable-document-manage: true
    enable-home-custom: false
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2025 智能文档系统 | CharmingDaiDai