spring:
  datasource:
    url: jdbc:mysql://10.0.30.172:13306/smart_doc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 50MB

# 应用配置
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # 一天
      refresh-token:
        expiration: 604800000 # 一周

# LLM配置
llm:
  openai:
    api-key: ${OPENAI_API_KEY:your-api-key-here}
    model: glm-4-flash
    embedding-model: bge-m3
    temperature: 0.7

# Milvus配置
milvus:
  host: 10.0.30.172
  port: 19530
  collection-name: document_vectors
  dimension: 1024

# MinIO配置
minio:
  endpoint: http://10.0.30.172:9000 #minio服务地址
  accessKey: root #minio的用户名
  secretKey: 12345678 #minio的密码
  bucket:
    files: smartdoc

# Knife4j 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '默认分组'
      paths-to-match: '/**'
      packages-to-scan: com.mtmn.smartdoc.controller
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
    enable-swagger-models: true
    enable-document-manage: true
    enable-home-custom: false
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2025 智能文档分析系统 | CharmingDaiDai